version: '3'
services:
  hadoop:
    build: .
    # image: wangwii/hadoop-base:latest
    privileged: true
    ports:
      - "2222:22"
      - "8088:8088"
      - "9870:9870"
    volumes:
      - ./src:/src
      - ./scripts:/scripts
      - ./services:/services
